jwt:
  expiration: 1000
  secretKey: 3xIowMMEk1+XTK0Od3N0q5sReRxFN4NcAh0YcnWPPH1qi0I2ZkiNevHCMzqIoc/4
  dTQew6WmrcCKkd1mkVEPJQ==
  expirationRt: 288000
  secretKeyRt: wKb5evPECr7CKe+GBkQAylp96zkk02+p0KxG1vAypRzy9W/VGxmBCfK4e4c5p0Vv
  /JAVUbhOHiuxIrBVZ1dbqQ==

spring:
  redis:
    host: localhost
    port: 6379